on: push
name: Test Script

jobs:
  test:
    name: Test SPM Executable
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nomnoml
        run: npm install -g nomnoml

      - name: Run Tests
        run: swift test